site_name: WB SDK
site_description: Python SDK для Wildberries API
site_url: https://github.com/RTHeLL/wbsdk

theme:
  name: readthedocs

docs_dir: docs

nav:
  - Главная: index.md
  - API Reference: api.md
  # - История версий: CHANGELOG.md
  # - CONTRIBUTING: CONTRIBUTING.md
  # - SECURITY: SECURITY.md
  # - CODE OF CONDUCT: CODE_OF_CONDUCT.md
  # - LICENSE: LICENSE

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
